"""Rename task.ml_service to task.ml_service_name

Revision ID: 3acc466475a7
Revises: 0abe79a62583
Create Date: 2024-09-13 20:30:50.681008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acc466475a7'
down_revision: Union[str, None] = '0abe79a62583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('ml_service_name', sa.String(), nullable=False))
    op.drop_constraint('task_ml_service_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'ml_service', ['ml_service_name'], ['name'])
    op.drop_column('task', 'ml_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('ml_service', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_ml_service_fkey', 'task', 'ml_service', ['ml_service'], ['name'])
    op.drop_column('task', 'ml_service_name')
    # ### end Alembic commands ###
